namespace: dpm
resources:
- user.yaml
- parcel.yaml
- notification.yaml
- web.yaml
- namespace.yaml
- client-urls.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:db85da3822ca87432045e8c8443ea99941d7aae12d9f2b488cbe898ef8b3b678
  name: notification
  newName: ghcr.io/dorm-parcel-manager/dpm/notification
- digest: sha256:d3157d2012110049507318790883e2cb070d7f15e7f97fce6ffed813fa28d8ca
  name: parcel
  newName: ghcr.io/dorm-parcel-manager/dpm/parcel
- digest: sha256:0622d76a41de4d1759b896e3847b204a0982358db8b91761698afc39c9d03ff8
  name: user
  newName: ghcr.io/dorm-parcel-manager/dpm/user
- digest: sha256:23f0bbb3a41cd60a37db4de34b02532ea648e530917a4f695e97689b04a25436
  name: web
  newName: ghcr.io/dorm-parcel-manager/dpm-web
