namespace: dpm
resources:
- user.yaml
- parcel.yaml
- notification.yaml
- web.yaml
- namespace.yaml
- client-urls.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:ea5876ec832ace2df61d6bab19fd6fe49e2f33f011d8837f1ec493c8e99f72a2
  name: notification
  newName: ghcr.io/dorm-parcel-manager/dpm/notification
- digest: sha256:6a4668a0a2caf834880a8fcdebc1ba1754871861f9ba48405307c2f11f6ccbb6
  name: parcel
  newName: ghcr.io/dorm-parcel-manager/dpm/parcel
- digest: sha256:122445ce20e03f2bb54f71510c18790a04523f4e0f976ac33d07f9b31fa78d30
  name: user
  newName: ghcr.io/dorm-parcel-manager/dpm/user
- digest: sha256:6b915a4e84bfeffba042a43574a61a39e025d30b8698312f21bd7d9240b239ce
  name: web
  newName: ghcr.io/dorm-parcel-manager/dpm-web
