namespace: dpm
resources:
- user.yaml
- parcel.yaml
- notification.yaml
- web.yaml
- namespace.yaml
- client-urls.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:e0a20c1824c6cffa4dcf1799accaed1ae2250b60785102253b76fa185f797ea1
  name: notification
  newName: ghcr.io/dorm-parcel-manager/dpm/notification
- digest: sha256:0093784e2091346473f6ff3ebb04f67ce4d3c15bfde42fedde6b54f151e95589
  name: parcel
  newName: ghcr.io/dorm-parcel-manager/dpm/parcel
- digest: sha256:6c758781e42e7bdfc7512b5320c8e027b4e485d6140ee1a43921ef595b86afbc
  name: user
  newName: ghcr.io/dorm-parcel-manager/dpm/user
- digest: sha256:af44ff045472b9b4e6b3de8ce04c15fa8e61319482061c47634575b219518ba0
  name: web
  newName: ghcr.io/dorm-parcel-manager/dpm-web
