namespace: dpm
resources:
- user.yaml
- parcel.yaml
- notification.yaml
- web.yaml
- namespace.yaml
- client-urls.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:db85da3822ca87432045e8c8443ea99941d7aae12d9f2b488cbe898ef8b3b678
  name: notification
  newName: ghcr.io/dorm-parcel-manager/dpm/notification
- digest: sha256:a8dd9920831ebdbbd131269fe30f8965687fd59a78ed6015740d67b2e8ad0678
  name: parcel
  newName: ghcr.io/dorm-parcel-manager/dpm/parcel
- digest: sha256:0622d76a41de4d1759b896e3847b204a0982358db8b91761698afc39c9d03ff8
  name: user
  newName: ghcr.io/dorm-parcel-manager/dpm/user
- digest: sha256:1cbe9abb8de3395693e6fab71c35136d075a982882cfe772077660979451cb13
  name: web
  newName: ghcr.io/dorm-parcel-manager/dpm-web
