namespace: dpm
resources:
- user.yaml
- parcel.yaml
- notification.yaml
- web.yaml
- namespace.yaml
- client-urls.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:867dabc5242a8b1176b41717e5cdbbc5ee402ea796fd5cf9b501fabfee57320a
  name: notification
  newName: ghcr.io/dorm-parcel-manager/dpm/notification
- digest: sha256:a8dd9920831ebdbbd131269fe30f8965687fd59a78ed6015740d67b2e8ad0678
  name: parcel
  newName: ghcr.io/dorm-parcel-manager/dpm/parcel
- digest: sha256:122445ce20e03f2bb54f71510c18790a04523f4e0f976ac33d07f9b31fa78d30
  name: user
  newName: ghcr.io/dorm-parcel-manager/dpm/user
- digest: sha256:337354d1fdf409a70e333284624082ad67aa5e75c23a6d8b92610d3b506b956b
  name: web
  newName: ghcr.io/dorm-parcel-manager/dpm-web
