namespace: dpm
resources:
- user.yaml
- parcel.yaml
- notification.yaml
- web.yaml
- namespace.yaml
- client-urls.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:e0a20c1824c6cffa4dcf1799accaed1ae2250b60785102253b76fa185f797ea1
  name: notification
  newName: ghcr.io/dorm-parcel-manager/dpm/notification
- digest: sha256:db5ceeda14c80230d6780a2dcdd69ea8b6968e54e5adc581ed9eb840087837b1
  name: parcel
  newName: ghcr.io/dorm-parcel-manager/dpm/parcel
- digest: sha256:6c758781e42e7bdfc7512b5320c8e027b4e485d6140ee1a43921ef595b86afbc
  name: user
  newName: ghcr.io/dorm-parcel-manager/dpm/user
- digest: sha256:2be1e967a54e6d2bdcc3f977edc5753ef3c3ec8097df1fee77b5a3dfc8dce069
  name: web
  newName: ghcr.io/dorm-parcel-manager/dpm-web
