namespace: dpm
resources:
- user.yaml
- namespace.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:db5ceeda14c80230d6780a2dcdd69ea8b6968e54e5adc581ed9eb840087837b1
  name: parcel
  newName: ghcr.io/dorm-parcel-manager/dpm/parcel
- digest: sha256:b2b509f091c1620b21ead58773f69802890b0a0d11bf110a145a764cfc1e212a
  name: user
  newName: ghcr.io/dorm-parcel-manager/dpm/user
