namespace: dpm
resources:
- user.yaml
- parcel.yaml
- notification.yaml
- web.yaml
- namespace.yaml
- client-urls.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:867dabc5242a8b1176b41717e5cdbbc5ee402ea796fd5cf9b501fabfee57320a
  name: notification
  newName: ghcr.io/dorm-parcel-manager/dpm/notification
- digest: sha256:a8dd9920831ebdbbd131269fe30f8965687fd59a78ed6015740d67b2e8ad0678
  name: parcel
  newName: ghcr.io/dorm-parcel-manager/dpm/parcel
- digest: sha256:9fe872e23638ddb44ac60cfb1154b0045c7e6f1344f826c65fc73122204ca62e
  name: user
  newName: ghcr.io/dorm-parcel-manager/dpm/user
- digest: sha256:c29aa1dae9e6f8bd1e14399b0e379d7e984717cad29188c43f9f0269cdc896b7
  name: web
  newName: ghcr.io/dorm-parcel-manager/dpm-web
