namespace: dpm
resources:
- user.yaml
- namespace.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:ee35bf31bcf6a67eed18639294d5703a067a62acd2c9df1f998b0c39603816ce
  name: user
  newName: ghcr.io/dorm-parcel-manager/dpm/user
