namespace: dpm
resources:
- user.yaml
- parcel.yaml
- web.yaml
- namespace.yaml
- client-urls.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:db5ceeda14c80230d6780a2dcdd69ea8b6968e54e5adc581ed9eb840087837b1
  name: parcel
  newName: ghcr.io/dorm-parcel-manager/dpm/parcel
- digest: sha256:be28f044d8db922bfbfc7c86c2ae5ba1aa418413608b43865aa2534d442f46b2
  name: user
  newName: ghcr.io/dorm-parcel-manager/dpm/user
- digest: sha256:c49f32e74eb1442fa67bdddc5c8c1749b4fad1622a1eb47dc284be7d8f1b2c9f
  name: web
  newName: ghcr.io/dorm-parcel-manager/dpm-web
