namespace: dpm
resources:
- user.yaml
- parcel.yaml
- web.yaml
- namespace.yaml
- client-urls.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:6ed39b0e2f5093ced5742afa1fbaee97be665d244ffa219d99a645d2cec40a73
  name: notification
  newName: ghcr.io/dorm-parcel-manager/dpm/notification
- digest: sha256:db5ceeda14c80230d6780a2dcdd69ea8b6968e54e5adc581ed9eb840087837b1
  name: parcel
  newName: ghcr.io/dorm-parcel-manager/dpm/parcel
- digest: sha256:6c758781e42e7bdfc7512b5320c8e027b4e485d6140ee1a43921ef595b86afbc
  name: user
  newName: ghcr.io/dorm-parcel-manager/dpm/user
- digest: sha256:7e26ebb00273c16bba93e8651b60d0b97853a3f99b67d2eff9a89a30a31a3f96
  name: web
  newName: ghcr.io/dorm-parcel-manager/dpm-web
