namespace: dpm
resources:
- user.yaml
- namespace.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:feb7d8dfb01106097d95ddf5992e39f07d7bafdefec770faa79c5469ab2c1fe1
  name: user
  newName: ghcr.io/dorm-parcel-manager/dpm/user
