apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 2
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: web
        env:
        - name: BASE_URL
          value: https://dpm.suphon.dev
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: google-oauth-client
              key: client-id
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: google-oauth-client
              key: client-secret
        - name: DEBUG_MODE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: debug-mode
              key: password
        envFrom:
        - configMapRef:
            name: client-urls
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: web
spec:
  ports:
  - port: 3000
    protocol: TCP
  selector:
    app: web
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: web-ingress

spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: Host(`dpm.suphon.dev`)
    services:
    - name: web
      port: 3000
