apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mongo
  name: mongo
  namespace: dpm
spec:
  replicas: 1
  selector:
      matchLabels:
        app: mongo
  serviceName: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - image: mongo:6.0.2
          name: mongo
          env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: dpm
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo
                key: password
          ports:
            - containerPort: 27017
              name: mongo
          volumeMounts:
            - mountPath: /data/db
              name: data
  volumeClaimTemplates:
  - metadata:
      name: data
      namespace: dpm
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10G
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: dpm
spec:
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017
  selector:
    app: mongo
  type: ClusterIP
