apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: postgres
  name: postgres
  namespace: dpm
spec:
  replicas: 1
  selector:
      matchLabels:
        app: postgres
  serviceName: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - image: postgres:14.5-alpine
          name: postgres
          env:
          - name: POSTGRES_USER
            value: dpm
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres
                key: password
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: data
  volumeClaimTemplates:
  - metadata:
      name: data
      namespace: dpm
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10G
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: dpm
spec:
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  selector:
    app: postgres
  type: ClusterIP
